### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jeffreywhitaker** [jonyonson/snapstock-fe#2]
When I click on a stock and it shows me the graph of the stock, i wanna be able to hover over the graph and have a little popup that says the day and price of the stock.

**Comment by jeffreywhitaker** [comment]
Also for the DOW and stuff on the top, I wanna be able to click them and be taken to a graph that shows them over time, like for the company stocks

**Comment by jonyonson** [comment]
No

**Comment by jonyonson** [comment]
I have the first thing on feature branch that I never finished. It is kind of janky with the library I am using. I really need to switch that library.  For the second indexes, those are proprietary and super expensive to subscribe to so API doesn't offer them.  I'm getting the updated index prices from a python library that is scraping the info, but don't really have access to the complete data for the indexes.
